# Generated by Django 2.2 on 2020-09-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='short_urls',
            name='long_url',
            field=models.URLField(verbose_name='URL'),
        ),
    ]
